---
version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=material_matchmaker
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - material_matchmaker_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  material_matchmaker_data:
